### ISSUE TITLE
Safe code path traversal not work

### ISSUE THREAD

**Issue by pipopi6** [dso-vcs/secure_coding_handbook#19]
https://github.com/dso-vcs/secure_coding_handbook/blame/15b02d6337e8b166cbae1661ad4a1b3719b133d4/Web/PHP/Basic/Path_Traversal.md#L30

**Comment by NhimDaiKa** [comment]
@pipopi6 fix lỗ hổng này

**Comment by NhimDaiKa** [comment]
lỗ hổng đã được fix ở #21
